version: '2'

services:
  server:
    build:
      context: ./
    ports:
      - "3000:3000"
    networks:
      - internal
      - outside
  postgresql:
    image: 'docker/postgresql:latest'
    volumes:
      - postgresql_data:/var/lib/postgresql
    networks:
      - internal

volumes:
  postgresql_data: {}

networks:
  internal:
    internal: true
  outside:
    driver: bridge
